### ISSUE TITLE
remove 'AuiNg'-prefix for non-components

### ISSUE THREAD

**Issue by xat** [K15t/aui-ng2#9]
AFAIR we don't have the name-clashing problems in ng2 like we had in ng1. Therefor I suggest we remove the 'AuiNg'-prefix for all non-Components (like services etc.). Anyhow, I would still keep the prefix within Components (this makes detecting AuiNg components easier in template snippets).

Also, maybe we can replace the 'AuiNg'-Prefix with something shorter? How about just 'Aui' or 'An' (like in aui-ng1)?

What is your opinion, @SvenWalter ?

**Comment by SvenWalter** [comment]
I think we should have the prefix because if you import a component it can clash with an already existing import e.g. DialogService is query common. You could rename the alias but I don't like that, plus the prefix makes it really clear it is from us. Regarding the 'AuiNg' prefix in general, I'm also struggling with the name. In the templates it tends to be also little bit unreadable ... Let's discuss that on Wednesday.

**Comment by xat** [comment]
I'll close this one for now :)
